package com.taobao.timetunnel.client.message;

/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
import java.nio.ByteBuffer;
import java.util.BitSet;
import java.util.Collections;
import java.util.EnumMap;
import java.util.EnumSet;
import java.util.HashMap;
import java.util.Map;

import org.apache.thrift.TBase;
import org.apache.thrift.TBaseHelper;
import org.apache.thrift.TException;
import org.apache.thrift.TFieldIdEnum;
import org.apache.thrift.TFieldRequirementType;
import org.apache.thrift.meta_data.FieldMetaData;
import org.apache.thrift.meta_data.FieldValueMetaData;
import org.apache.thrift.meta_data.MapMetaData;
import org.apache.thrift.protocol.TField;
import org.apache.thrift.protocol.TMap;
import org.apache.thrift.protocol.TProtocol;
import org.apache.thrift.protocol.TProtocolUtil;
import org.apache.thrift.protocol.TStruct;
import org.apache.thrift.protocol.TType;

@SuppressWarnings(value = { "unchecked", "serial" })
public class MessageStruct implements TBase<MessageStruct, MessageStruct._Fields>, java.io.Serializable, Cloneable {
	private static final TStruct STRUCT_DESC = new TStruct("MessageStruct");

	private static final TField TOPIC_FIELD_DESC = new TField("topic", TType.STRING, (short) 1);
	private static final TField CONTENT_FIELD_DESC = new TField("content", TType.STRING, (short) 2);
	private static final TField CREATED_TIME_FIELD_DESC = new TField("createdTime", TType.I64, (short) 3);
	private static final TField ID_FIELD_DESC = new TField("id", TType.STRING, (short) 4);
	private static final TField IP_ADDRESS_FIELD_DESC = new TField("ipAddress", TType.STRING, (short) 5);
	private static final TField PROPS_FIELD_DESC = new TField("props", TType.MAP, (short) 6);

	public String topic;
	public ByteBuffer content;
	public long createdTime;
	public String id;
	public String ipAddress;
	public Map<String, String> props;

	/**
	 * The set of fields this struct contains, along with convenience methods
	 * for finding and manipulating them.
	 */
	public enum _Fields implements TFieldIdEnum {
		TOPIC((short) 1, "topic"), CONTENT((short) 2, "content"), CREATED_TIME((short) 3, "createdTime"), ID((short) 4, "id"), IP_ADDRESS((short) 5, "ipAddress"), PROPS((short) 6, "props");

		private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

		static {
			for (_Fields field : EnumSet.allOf(_Fields.class)) {
				byName.put(field.getFieldName(), field);
			}
		}

		/**
		 * Find the _Fields constant that matches fieldId, or null if its not
		 * found.
		 */
		public static _Fields findByThriftId(int fieldId) {
			switch (fieldId) {
			case 1: // TOPIC
				return TOPIC;
			case 2: // CONTENT
				return CONTENT;
			case 3: // CREATED_TIME
				return CREATED_TIME;
			case 4: // ID
				return ID;
			case 5: // IP_ADDRESS
				return IP_ADDRESS;
			case 6: // PROPS
				return PROPS;
			default:
				return null;
			}
		}

		/**
		 * Find the _Fields constant that matches fieldId, throwing an exception
		 * if it is not found.
		 */
		public static _Fields findByThriftIdOrThrow(int fieldId) {
			_Fields fields = findByThriftId(fieldId);
			if (fields == null)
				throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
			return fields;
		}

		/**
		 * Find the _Fields constant that matches name, or null if its not
		 * found.
		 */
		public static _Fields findByName(String name) {
			return byName.get(name);
		}

		private final short _thriftId;
		private final String _fieldName;

		_Fields(short thriftId, String fieldName) {
			_thriftId = thriftId;
			_fieldName = fieldName;
		}

		public short getThriftFieldId() {
			return _thriftId;
		}

		public String getFieldName() {
			return _fieldName;
		}
	}

	// isset id assignments
	private static final int __CREATEDTIME_ISSET_ID = 0;
	private BitSet __isset_bit_vector = new BitSet(1);

	public static final Map<_Fields, FieldMetaData> metaDataMap;
	static {
		Map<_Fields, FieldMetaData> tmpMap = new EnumMap<_Fields, FieldMetaData>(_Fields.class);
		tmpMap.put(_Fields.TOPIC, new FieldMetaData("topic", TFieldRequirementType.DEFAULT, new FieldValueMetaData(TType.STRING)));
		tmpMap.put(_Fields.CONTENT, new FieldMetaData("content", TFieldRequirementType.DEFAULT, new FieldValueMetaData(TType.STRING)));
		tmpMap.put(_Fields.CREATED_TIME, new FieldMetaData("createdTime", TFieldRequirementType.DEFAULT, new FieldValueMetaData(TType.I64)));
		tmpMap.put(_Fields.ID, new FieldMetaData("id", TFieldRequirementType.DEFAULT, new FieldValueMetaData(TType.STRING)));
		tmpMap.put(_Fields.IP_ADDRESS, new FieldMetaData("ipAddress", TFieldRequirementType.DEFAULT, new FieldValueMetaData(TType.STRING)));
		tmpMap.put(_Fields.PROPS, new FieldMetaData("props", TFieldRequirementType.DEFAULT, new MapMetaData(TType.MAP, new FieldValueMetaData(TType.STRING), new FieldValueMetaData(TType.STRING))));
		metaDataMap = Collections.unmodifiableMap(tmpMap);
		FieldMetaData.addStructMetaDataMap(MessageStruct.class, metaDataMap);
	}

	public MessageStruct() {
	}

	public MessageStruct(String topic, ByteBuffer content, long createdTime, String id, String ipAddress, Map<String, String> props) {
		this();
		this.topic = topic;
		this.content = content;
		this.createdTime = createdTime;
		setCreatedTimeIsSet(true);
		this.id = id;
		this.ipAddress = ipAddress;
		this.props = props;
	}

	/**
	 * Performs a deep copy on <i>other</i>.
	 */
	public MessageStruct(MessageStruct other) {
		__isset_bit_vector.clear();
		__isset_bit_vector.or(other.__isset_bit_vector);
		if (other.isSetTopic()) {
			this.topic = other.topic;
		}
		if (other.isSetContent()) {
			this.content = TBaseHelper.copyBinary(other.content);
			;
		}
		this.createdTime = other.createdTime;
		if (other.isSetId()) {
			this.id = other.id;
		}
		if (other.isSetIpAddress()) {
			this.ipAddress = other.ipAddress;
		}
		if (other.isSetProps()) {
			Map<String, String> __this__props = new HashMap<String, String>();
			for (Map.Entry<String, String> other_element : other.props.entrySet()) {

				String other_element_key = other_element.getKey();
				String other_element_value = other_element.getValue();

				String __this__props_copy_key = other_element_key;

				String __this__props_copy_value = other_element_value;

				__this__props.put(__this__props_copy_key, __this__props_copy_value);
			}
			this.props = __this__props;
		}
	}

	public MessageStruct deepCopy() {
		return new MessageStruct(this);
	}

	@Override
	public void clear() {
		this.topic = null;
		this.content = null;
		setCreatedTimeIsSet(false);
		this.createdTime = 0;
		this.id = null;
		this.ipAddress = null;
		this.props = null;
	}

	public String getTopic() {
		return this.topic;
	}

	public MessageStruct setTopic(String topic) {
		this.topic = topic;
		return this;
	}

	public void unsetTopic() {
		this.topic = null;
	}

	/**
	 * Returns true if field topic is set (has been asigned a value) and false
	 * otherwise
	 */
	public boolean isSetTopic() {
		return this.topic != null;
	}

	public void setTopicIsSet(boolean value) {
		if (!value) {
			this.topic = null;
		}
	}

	public byte[] getContent() {
		setContent(TBaseHelper.rightSize(content));
		return content.array();
	}

	public ByteBuffer BufferForContent() {
		return content;
	}

	public MessageStruct setContent(byte[] content) {
		setContent(ByteBuffer.wrap(content));
		return this;
	}

	public MessageStruct setContent(ByteBuffer content) {
		this.content = content;
		return this;
	}

	public void unsetContent() {
		this.content = null;
	}

	/**
	 * Returns true if field content is set (has been asigned a value) and false
	 * otherwise
	 */
	public boolean isSetContent() {
		return this.content != null;
	}

	public void setContentIsSet(boolean value) {
		if (!value) {
			this.content = null;
		}
	}

	public long getCreatedTime() {
		return this.createdTime;
	}

	public MessageStruct setCreatedTime(long createdTime) {
		this.createdTime = createdTime;
		setCreatedTimeIsSet(true);
		return this;
	}

	public void unsetCreatedTime() {
		__isset_bit_vector.clear(__CREATEDTIME_ISSET_ID);
	}

	/**
	 * Returns true if field createdTime is set (has been asigned a value) and
	 * false otherwise
	 */
	public boolean isSetCreatedTime() {
		return __isset_bit_vector.get(__CREATEDTIME_ISSET_ID);
	}

	public void setCreatedTimeIsSet(boolean value) {
		__isset_bit_vector.set(__CREATEDTIME_ISSET_ID, value);
	}

	public String getId() {
		return this.id;
	}

	public MessageStruct setId(String id) {
		this.id = id;
		return this;
	}

	public void unsetId() {
		this.id = null;
	}

	/**
	 * Returns true if field id is set (has been asigned a value) and false
	 * otherwise
	 */
	public boolean isSetId() {
		return this.id != null;
	}

	public void setIdIsSet(boolean value) {
		if (!value) {
			this.id = null;
		}
	}

	public String getIpAddress() {
		return this.ipAddress;
	}

	public MessageStruct setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
		return this;
	}

	public void unsetIpAddress() {
		this.ipAddress = null;
	}

	/**
	 * Returns true if field ipAddress is set (has been asigned a value) and
	 * false otherwise
	 */
	public boolean isSetIpAddress() {
		return this.ipAddress != null;
	}

	public void setIpAddressIsSet(boolean value) {
		if (!value) {
			this.ipAddress = null;
		}
	}

	public int getPropsSize() {
		return (this.props == null) ? 0 : this.props.size();
	}

	public void putToProps(String key, String val) {
		if (this.props == null) {
			this.props = new HashMap<String, String>();
		}
		this.props.put(key, val);
	}

	public Map<String, String> getProps() {
		return this.props;
	}

	public MessageStruct setProps(Map<String, String> props) {
		this.props = props;
		return this;
	}

	public void unsetProps() {
		this.props = null;
	}

	/**
	 * Returns true if field props is set (has been asigned a value) and false
	 * otherwise
	 */
	public boolean isSetProps() {
		return this.props != null;
	}

	public void setPropsIsSet(boolean value) {
		if (!value) {
			this.props = null;
		}
	}

	public void setFieldValue(_Fields field, Object value) {
		switch (field) {
		case TOPIC:
			if (value == null) {
				unsetTopic();
			} else {
				setTopic((String) value);
			}
			break;

		case CONTENT:
			if (value == null) {
				unsetContent();
			} else {
				setContent((ByteBuffer) value);
			}
			break;

		case CREATED_TIME:
			if (value == null) {
				unsetCreatedTime();
			} else {
				setCreatedTime((Long) value);
			}
			break;

		case ID:
			if (value == null) {
				unsetId();
			} else {
				setId((String) value);
			}
			break;

		case IP_ADDRESS:
			if (value == null) {
				unsetIpAddress();
			} else {
				setIpAddress((String) value);
			}
			break;

		case PROPS:
			if (value == null) {
				unsetProps();
			} else {
				setProps((Map<String, String>) value);
			}
			break;

		}
	}

	public Object getFieldValue(_Fields field) {
		switch (field) {
		case TOPIC:
			return getTopic();

		case CONTENT:
			return getContent();

		case CREATED_TIME:
			return new Long(getCreatedTime());

		case ID:
			return getId();

		case IP_ADDRESS:
			return getIpAddress();

		case PROPS:
			return getProps();

		}
		throw new IllegalStateException();
	}

	/**
	 * Returns true if field corresponding to fieldID is set (has been asigned a
	 * value) and false otherwise
	 */
	public boolean isSet(_Fields field) {
		if (field == null) {
			throw new IllegalArgumentException();
		}

		switch (field) {
		case TOPIC:
			return isSetTopic();
		case CONTENT:
			return isSetContent();
		case CREATED_TIME:
			return isSetCreatedTime();
		case ID:
			return isSetId();
		case IP_ADDRESS:
			return isSetIpAddress();
		case PROPS:
			return isSetProps();
		}
		throw new IllegalStateException();
	}

	@Override
	public boolean equals(Object that) {
		if (that == null)
			return false;
		if (that instanceof MessageStruct)
			return this.equals((MessageStruct) that);
		return false;
	}

	public boolean equals(MessageStruct that) {
		if (that == null)
			return false;

		boolean this_present_topic = true && this.isSetTopic();
		boolean that_present_topic = true && that.isSetTopic();
		if (this_present_topic || that_present_topic) {
			if (!(this_present_topic && that_present_topic))
				return false;
			if (!this.topic.equals(that.topic))
				return false;
		}

		boolean this_present_content = true && this.isSetContent();
		boolean that_present_content = true && that.isSetContent();
		if (this_present_content || that_present_content) {
			if (!(this_present_content && that_present_content))
				return false;
			if (!this.content.equals(that.content))
				return false;
		}

		boolean this_present_createdTime = true;
		boolean that_present_createdTime = true;
		if (this_present_createdTime || that_present_createdTime) {
			if (!(this_present_createdTime && that_present_createdTime))
				return false;
			if (this.createdTime != that.createdTime)
				return false;
		}

		boolean this_present_id = true && this.isSetId();
		boolean that_present_id = true && that.isSetId();
		if (this_present_id || that_present_id) {
			if (!(this_present_id && that_present_id))
				return false;
			if (!this.id.equals(that.id))
				return false;
		}

		boolean this_present_ipAddress = true && this.isSetIpAddress();
		boolean that_present_ipAddress = true && that.isSetIpAddress();
		if (this_present_ipAddress || that_present_ipAddress) {
			if (!(this_present_ipAddress && that_present_ipAddress))
				return false;
			if (!this.ipAddress.equals(that.ipAddress))
				return false;
		}

		boolean this_present_props = true && this.isSetProps();
		boolean that_present_props = true && that.isSetProps();
		if (this_present_props || that_present_props) {
			if (!(this_present_props && that_present_props))
				return false;
			if (!this.props.equals(that.props))
				return false;
		}

		return true;
	}

	@Override
	public int hashCode() {
		return 0;
	}

	public int compareTo(MessageStruct other) {
		if (!getClass().equals(other.getClass())) {
			return getClass().getName().compareTo(other.getClass().getName());
		}

		int lastComparison = 0;
		MessageStruct typedOther = (MessageStruct) other;

		lastComparison = Boolean.valueOf(isSetTopic()).compareTo(typedOther.isSetTopic());
		if (lastComparison != 0) {
			return lastComparison;
		}
		if (isSetTopic()) {
			lastComparison = TBaseHelper.compareTo(this.topic, typedOther.topic);
			if (lastComparison != 0) {
				return lastComparison;
			}
		}
		lastComparison = Boolean.valueOf(isSetContent()).compareTo(typedOther.isSetContent());
		if (lastComparison != 0) {
			return lastComparison;
		}
		if (isSetContent()) {
			lastComparison = TBaseHelper.compareTo(this.content, typedOther.content);
			if (lastComparison != 0) {
				return lastComparison;
			}
		}
		lastComparison = Boolean.valueOf(isSetCreatedTime()).compareTo(typedOther.isSetCreatedTime());
		if (lastComparison != 0) {
			return lastComparison;
		}
		if (isSetCreatedTime()) {
			lastComparison = TBaseHelper.compareTo(this.createdTime, typedOther.createdTime);
			if (lastComparison != 0) {
				return lastComparison;
			}
		}
		lastComparison = Boolean.valueOf(isSetId()).compareTo(typedOther.isSetId());
		if (lastComparison != 0) {
			return lastComparison;
		}
		if (isSetId()) {
			lastComparison = TBaseHelper.compareTo(this.id, typedOther.id);
			if (lastComparison != 0) {
				return lastComparison;
			}
		}
		lastComparison = Boolean.valueOf(isSetIpAddress()).compareTo(typedOther.isSetIpAddress());
		if (lastComparison != 0) {
			return lastComparison;
		}
		if (isSetIpAddress()) {
			lastComparison = TBaseHelper.compareTo(this.ipAddress, typedOther.ipAddress);
			if (lastComparison != 0) {
				return lastComparison;
			}
		}
		lastComparison = Boolean.valueOf(isSetProps()).compareTo(typedOther.isSetProps());
		if (lastComparison != 0) {
			return lastComparison;
		}
		if (isSetProps()) {
			lastComparison = TBaseHelper.compareTo(this.props, typedOther.props);
			if (lastComparison != 0) {
				return lastComparison;
			}
		}
		return 0;
	}

	public _Fields fieldForId(int fieldId) {
		return _Fields.findByThriftId(fieldId);
	}

	public void read(TProtocol iprot) throws TException {
		TField field;
		iprot.readStructBegin();
		while (true) {
			field = iprot.readFieldBegin();
			if (field.type == TType.STOP) {
				break;
			}
			switch (field.id) {
			case 1: // TOPIC
				if (field.type == TType.STRING) {
					this.topic = iprot.readString();
				} else {
					TProtocolUtil.skip(iprot, field.type);
				}
				break;
			case 2: // CONTENT
				if (field.type == TType.STRING) {
					this.content = iprot.readBinary();
				} else {
					TProtocolUtil.skip(iprot, field.type);
				}
				break;
			case 3: // CREATED_TIME
				if (field.type == TType.I64) {
					this.createdTime = iprot.readI64();
					setCreatedTimeIsSet(true);
				} else {
					TProtocolUtil.skip(iprot, field.type);
				}
				break;
			case 4: // ID
				if (field.type == TType.STRING) {
					this.id = iprot.readString();
				} else {
					TProtocolUtil.skip(iprot, field.type);
				}
				break;
			case 5: // IP_ADDRESS
				if (field.type == TType.STRING) {
					this.ipAddress = iprot.readString();
				} else {
					TProtocolUtil.skip(iprot, field.type);
				}
				break;
			case 6: // PROPS
				if (field.type == TType.MAP) {
					{
						TMap _map0 = iprot.readMapBegin();
						this.props = new HashMap<String, String>(2 * _map0.size);
						for (int _i1 = 0; _i1 < _map0.size; ++_i1) {
							String _key2;
							String _val3;
							_key2 = iprot.readString();
							_val3 = iprot.readString();
							this.props.put(_key2, _val3);
						}
						iprot.readMapEnd();
					}
				} else {
					TProtocolUtil.skip(iprot, field.type);
				}
				break;
			default:
				TProtocolUtil.skip(iprot, field.type);
			}
			iprot.readFieldEnd();
		}
		iprot.readStructEnd();

		// check for required fields of primitive type, which can't be checked
		// in the validate method
		validate();
	}

	public void write(TProtocol oprot) throws TException {
		validate();

		oprot.writeStructBegin(STRUCT_DESC);
		if (this.topic != null) {
			oprot.writeFieldBegin(TOPIC_FIELD_DESC);
			oprot.writeString(this.topic);
			oprot.writeFieldEnd();
		}
		if (this.content != null) {
			oprot.writeFieldBegin(CONTENT_FIELD_DESC);
			oprot.writeBinary(this.content);
			oprot.writeFieldEnd();
		}
		oprot.writeFieldBegin(CREATED_TIME_FIELD_DESC);
		oprot.writeI64(this.createdTime);
		oprot.writeFieldEnd();
		if (this.id != null) {
			oprot.writeFieldBegin(ID_FIELD_DESC);
			oprot.writeString(this.id);
			oprot.writeFieldEnd();
		}
		if (this.ipAddress != null) {
			oprot.writeFieldBegin(IP_ADDRESS_FIELD_DESC);
			oprot.writeString(this.ipAddress);
			oprot.writeFieldEnd();
		}
		if (this.props != null) {
			oprot.writeFieldBegin(PROPS_FIELD_DESC);
			{
				oprot.writeMapBegin(new TMap(TType.STRING, TType.STRING, this.props.size()));
				for (Map.Entry<String, String> _iter4 : this.props.entrySet()) {
					oprot.writeString(_iter4.getKey());
					oprot.writeString(_iter4.getValue());
				}
				oprot.writeMapEnd();
			}
			oprot.writeFieldEnd();
		}
		oprot.writeFieldStop();
		oprot.writeStructEnd();
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("MessageStruct(");
		boolean first = true;

		sb.append("topic:");
		if (this.topic == null) {
			sb.append("null");
		} else {
			sb.append(this.topic);
		}
		first = false;
		if (!first)
			sb.append(", ");
		sb.append("content:");
		if (this.content == null) {
			sb.append("null");
		} else {
			TBaseHelper.toString(this.content, sb);
		}
		first = false;
		if (!first)
			sb.append(", ");
		sb.append("createdTime:");
		sb.append(this.createdTime);
		first = false;
		if (!first)
			sb.append(", ");
		sb.append("id:");
		if (this.id == null) {
			sb.append("null");
		} else {
			sb.append(this.id);
		}
		first = false;
		if (!first)
			sb.append(", ");
		sb.append("ipAddress:");
		if (this.ipAddress == null) {
			sb.append("null");
		} else {
			sb.append(this.ipAddress);
		}
		first = false;
		if (!first)
			sb.append(", ");
		sb.append("props:");
		if (this.props == null) {
			sb.append("null");
		} else {
			sb.append(this.props);
		}
		first = false;
		sb.append(")");
		return sb.toString();
	}

	public void validate() throws TException {
		// check for required fields
	}

}
