/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.taobao.timetunnel.thrift.router;

import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class Constants {

  public static final String LOCAL_HOST = "host";

  public static final String TYPE = "type";

  public static final String RECVWINSIZE = "size";  

  public static final String TIMEOUT = "timeout";

  public static final String SUBSCRIBER = "subscriber";

}
